export const A = {
  FAILURE: "FAILURE",
  ALERT_ERROR: "ALERT_ERROR",

  UPDATE_USER_STORE: "UPDATE_USER_STORE",

  CREATE_COURSE: "CREATE_COURSE",
  LOAD_COURSES_SUCCESS: "LOAD_COURSES_SUCCESS",

  LOAD_NAVIGATION_REQUEST: "LOAD_NAVIGATION_REQUEST",
  LOAD_NAVIGATION_SUCCESS: "LOAD_NAVIGATION_SUCCESS",
  LOAD_NAVIGATION_FAILURE: "LOAD_NAVIGATION_FAILURE",

  GET_SERVICE_DATA_REQUEST: 'GET_SERVICE_DATA_REQUEST',
  GET_SERVICE_DATA_SUCCESS: 'GET_SERVICE_DATA_SUCCESS',
  GET_SERVICE_DATA_FAILURE: 'GET_SERVICE_DATA_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  USER_INFO_REQUEST: 'USER_INFO_REQUEST',
  USER_INFO_SUCCESS: 'USER_INFO_SUCCESS',
  USER_INFO_FAILURE: 'USER_INFO_FAILURE',
  USER_LOGOUT: 'USER_LOGOUT',

  REGISTRATION_REQUEST: 'REGISTRATION_REQUEST',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  REGISTRATION_FAILURE: 'REGISTRATION_FAILURE',
};
